### ISSUE TITLE
Outdated Congressional Districts

### ISSUE THREAD

**Issue by Makosak** [GeoDaCenter/covid-v3#46]
US Congressional District datasets have since changed. Either indicate vintage, add new, or remove.
<img width="1649" alt="Screen Shot 2023-09-12 at 1 37 49 PM" src="https://github.com/GeoDaCenter/covid-v3/assets/4277692/f2fb6694-8aa8-47ed-8f30-41b32914bc6a">

**Comment by Makosak** [comment]
@mradamcox what are your thoughts on this?

**Comment by mradamcox** [comment]
I'd say just adding the year would be good enough.

**Comment by Makosak** [comment]
Add the date to label, update data doc, then close
