### ISSUE TITLE
Remove obsolete /docs and /docs/vintage directories

### ISSUE THREAD

**Issue by mradamcox** [GeoDaCenter/covid-v3#54]
As far as @mukeshchugani10 and I can tell, these directories hold early static versions of the site that are now no longer used in any way. We think they can probably be completely removed.

Things to check before doing so:

- [x] no assets within are used elsewhere in the app
- [x] there are no hard-coded links that somehow point to these pages
- [x] anything else?

**Comment by mradamcox** [comment]
@nofurtherinformation @spaykin any input on this much appreciated :)

**Comment by nofurtherinformation** [comment]
Hey @mradamcox - the vintage directories were from when we first refactored to react, and there was a request to retain the previous version of the site (so those can definitely be deleted). The `docs` directory hosts generated docs for the [component docs site](https://docs.uscovidatlas.org/) I put together -- these may be deployable straight from Netlify if you'd still want them but don't want to retain in the repo itself!

**Comment by mradamcox** [comment]
Thanks @nofurtherinformation, I did find the components docs site subdomain, but I believe it's generated on the fly with jsdocs in Netlify, and doesn't touch the /docs directory at all. So it sounds like we can safely go ahead and remove this content.
