### ISSUE TITLE
Fix style of stories markers on map

### ISSUE THREAD

**Issue by mradamcox** [GeoDaCenter/covid-v3#61]
The markers are too big when there are multiple items in a cluster:

![image](https://github.com/GeoDaCenter/covid-v3/assets/10427268/283df1ca-71b7-4086-a256-76e946ce6253)

This layer is created via a JSON file that is acquired via CDN. There should be a line or two of MapboxGL-JS code that defines its style within this code-base.

**Comment by mukeshchugani10** [comment]
Fixed in #64 . Closing now.
